Added settings button and updated styles
markvandal/mb.core.cr.wallet pull request #18
Opened 2021-04-10 11:55 UTC by Copermaine

2021-04-10 11:59 UTC, markvandal requested changes
1. Please fix white spaces in your IDE (I'd recommend to use VS code with it's autoformatting configured for double space per tab).
2. Restore missing files.

2021-04-10 11:59 UTC, markvandal commented on .env.copy
> -DEBUG_AUTH=""
Please restore the file

2021-04-10 11:59 UTC, markvandal commented on .gitignore
> -.env.copy*
Please restore the entery

2021-04-10 11:59 UTC, markvandal commented on components/header.js
> +                        iconSize={25}
White spaces should be double space per tab. Please fix.

2021-04-11 09:05 UTC, Copermaine commented
Double space per tab fixed.

2021-04-11 10:27 UTC, Copermaine commented
Restore env

2021-04-11 10:49 UTC, jackmb1 commented on .gitignore
> -.env.copy*
and probably make sense to ignore `/.idea/` folder as it's your env specific stuff

2021-04-11 11:02 UTC, jackmb1 commented on package.json
> +    "uuid": "^3.4.0",
has `package-lock.json` been changed as well? https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json

2021-04-13 08:56 UTC, markvandal requested changes

2021-04-13 08:56 UTC, markvandal commented on .gitignore
> -.env.copy*
idea is still here )

2021-04-13 09:23 UTC, closed without merging

2021-04-13 09:23 UTC, Copermaine commented
Close